[package]
name = "disk-watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
fs_extra = "1.3.0"
clap = { "version" = "4.5.20", features = ["env", "derive"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
log = "0.4.22"
env_logger = "0.11.5"
