name: Rust CI

on:
  push:
    branches:
      - main  # Spustí se při push do hlavní větve

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Publish artifacts
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: disk-watcher
          target: ${{ matrix.platform.target }}
          release-tag-prefix: ""
      - name: Tag the repository
        id: tag
        run: |
          # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: target/${{ matrix.platform.target }}/release/disk-watcher
        env:
          GITHUB_TOKEN: ${{ steps.tag.outputs.tag }}