name: Rust CI

on:
  push:
    branches:
      - main  # Spustí se při push do hlavní větve

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Publish artifacts
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: disk-watcher
          target: ${{ matrix.platform.target }}
          release-tag-prefix: ""
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: target/${{ matrix.platform.target }}/release/disk-watcher
          tag_name: ${{ steps.bump.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ steps.bump.outputs.new_tag }}